### ISSUE TITLE
npm install doesn't install the right version

### ISSUE THREAD

**Issue by dwoodlock** [taylorhakes/promise-mock#1]
Hi there,
I like the concept of your library.  When I did an npm install promise-mock, the code I got was missing the PromiseMock.getResult method and it differs from the code that I can see in the github.  Specifically, what I see when I look at index.js in githib is 90 lines long.  When I got in my node_modules when I did an install was 72 lines long and missing that method.  Thanks.  
Don

**Comment by dotdat** [comment]
I'd like to second this. getResult is a really useful function to have. I'd rather point my package.json file at an npm package than a github commit. Would you consider publishing this as a 1.1.0 release?

**Comment by taylorhakes** [comment]
Sorry for the delay. This is fixed in version 1.1.0
