### ISSUE TITLE
`new Promise()` doesn't have a `.then` method!

### ISSUE THREAD

**Issue by togakangaroo** [taylorhakes/promise-mock#2]
Kind of a problem when you use `new Promise()` to create promises and deferred objects

This took waay too long to track down because it breaks code elsewhere but this shows `[Function]` followed by `undefined`

```
beforeEach(() => {
  console.log(new Promise(() => {}).then)
  promiseMock.install()
  console.log(new Promise(() => {}).then)
} )

```

**Comment by scamden** [comment]
just ran into this. dude, this is pretty major....

**Comment by scamden** [comment]
@taylorhakes this is totally broken in this state, any chance you could fix?

**Comment by taylorhakes** [comment]
@scamden Sorry you ran into this. I don't have access to my computer until tomorrow. I will take a look tomorrow.

**Comment by scamden** [comment]
i think this fixes it: https://github.com/taylorhakes/promise-mock/pull/3
