### ISSUE TITLE
yairr89

### ISSUE THREAD

**Issue by yairr89** [taylorhakes/promise-mock#5]
Hi,

I'm using promise-mock version 1.1.0, and I've started to get the following exception when running tests: "Uncaught TypeError: PromiseMock._setImmediateFn is not a function".
This exception is thrown even if I upgrade to the latest version (1.1.1).
When I looked at the package.json file, I saw that promise-mock has a dependency in the module promise-polyfill with the version '*'.
Two days ago, the major version of promise-polyfill was changed from 6.1.0 to 7.0.0, so it looks like a breaking change was done.
If I change the dependency's version in promise-mock's package.json in my node_modules folder from '*' to '6.1.0', everything works.

**Comment by taylorhakes** [comment]
Thanks for the report. Sorry for the issue. I will update the library
tomorrow to fix.

**Comment by taylorhakes** [comment]
Fixed the issue @yairr89 in version 1.1.2

**Comment by yairr89** [comment]
Looks great! Thanks!
