### ISSUE TITLE
Promise polyfill gives an error with ES Modules

### ISSUE THREAD

**Issue by the-spyke** [taylorhakes/promise-mock#6]
In case of using bundlers such as Webpack, I get an error:

`Uncaught TypeError: Object prototype may only be an Object or null: undefined` 

The cause is in this line of `index.js`:

```javascript
var Promise = require('promise-polyfill'),
```

The `promise-polyfill` exposes ES Modules entry, which will be used by Webpack. What means that there will appear  `default` export:

 ```javascript
var Promise = require('promise-polyfill').deafult,
```

There are 2 potential solutions:

1. Do not include polyfills (best option?)
2. Add ES Modules entry too

**Comment by taylorhakes** [comment]
Thanks for the bug report. `promise-polyfill` is a required dependency of this library. I updated the library to support ES6 modules in version 2.0.0. See more info here 

https://github.com/taylorhakes/promise-mock/releases/tag/2.0.0

**Comment by the-spyke** [comment]
Now it gives a slightly different error:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

I think you should not mix `import` and `module.exports` in one file. And replacing

```
module.exports = PromiseMock;
```
with
```
export default PromiseMock;
```
resolves the issue for me.

**Comment by taylorhakes** [comment]
Ok, thanks. Made the update in 2.0.1

**Comment by the-spyke** [comment]
Now it works. Thank you!
