### ISSUE TITLE
Feature request: PromiseMock.flush, which doesn't throw

### ISSUE THREAD

**Issue by joeyparrish** [taylorhakes/promise-mock#7]
I'm working on integration PromiseMock with my project, and so far, it is really helping!

I've found that `PromiseMock.runAll()` throws if `waiting.length == 0`.  For my purposes, this is not helpful.

Therefore I propose the addition of `PromiseMock.flush`:

```js
PromiseMock.flush = function flush() {
  if (PromiseMock.waiting.length) {
    PromiseMock.runAll();
  }
};
```

Thoughts?

**Comment by taylorhakes** [comment]
@joeyparrish That makes sense. I was trying to be helpful, but I understand that sometimes you don't know whether a Promise is waiting. I will add a function

**Comment by taylorhakes** [comment]
I added `Promise.runAll(false)` to be the equivalent of flush you described above.

**Comment by joeyparrish** [comment]
Perfect.  Thanks!
